export var NormalRadarInfo =[
    {
        "label":"自我完整",
        "value":135
    },{
        "label":"攻击性",
        "value":90
    },{
        "label":"廉价感",
        "value":75
    },{
        "label":"幸福感",
        "value":30
    },{
        "label":"理性",
        "value":125
    },{
        "label":"自敬感",
        "value":115
    }
];
export var JobRadarInfo =[
    {
        "label":"D",
        "max":25,
        "value":19
    },{
        "label":"I",
        "max":25,
        "value":3
    },{
        "label":"S",
        "max":25,
        "value":3
    },{
        "label":"C",
        "max":25,
        "value":15
    }
];
export var SkillRadarInfo =[
    {
        "label":"CSS",
        "max":120,
        "value":88
    },{
        "label":"Java-\nScript",
        "max":120,
        "value":113
    },{
        "label":"Node.js",
        "max":120,
        "value":70
    },{
        "label":"PHP",
        "max":120,
        "value":65
    },{
        "label":"DB",
        "max":120,
        "value":60
    },{
        "label":"UI设计",
        "max":120,
        "value":82
    }
];
export var AcgRadarInfo =[
    {
        "label":"黑化",
        "value":139
    },{
        "label":"傲娇",
        "value":93
    },{
        "label":"独行",
        "value":120
    },{
        "label":"装傻",
        "value":85
    },{
        "label":"吐槽",
        "value":70
    },{
        "label":"理性",
        "value":149
    }
];